#!/usr/bin/env python3
"""
export_quality_checks.py
------------------------
Convert ByeDataClean schema and validation rules into starter files for
dbt, Pandera, and Soda Core.

Generated files are starter templates — review and adapt before using in
production pipelines. Business metadata (severity, owner) is preserved
as comments where supported.

Usage
-----
  python python/export_quality_checks.py \\
    --rules config/example_business_cleaning_rules.yaml \\
    --target dbt \\
    --output exports/

  python python/export_quality_checks.py \\
    --schema config/schema.example.yaml \\
    --rules  config/example_business_cleaning_rules.yaml \\
    --target pandera \\
    --output exports/

  python python/export_quality_checks.py \\
    --rules config/example_business_cleaning_rules.yaml \\
    --target soda \\
    --output exports/
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent))

import yaml

from toolkit.config import load_rules


# ── dbt exporter ──────────────────────────────────────────────────────────────

def export_dbt(
    validation: dict[str, Any],
    output_dir: Path,
    model_name: str = "my_model",
    rules_path: str = "",
) -> Path:
    """Generate a dbt schema.yml from the validation section of a rules file."""
    required_cols: list[str] = validation.get("required_columns") or []
    unique_keys: list[list[str]] = validation.get("unique_keys") or []
    accepted_values: dict[str, list] = validation.get("accepted_values") or {}
    ranges: dict[str, dict] = validation.get("ranges") or {}

    # Collect all columns mentioned anywhere
    all_cols: set[str] = set(required_cols) | set(accepted_values) | set(ranges)
    for key_group in unique_keys:
        all_cols.update(key_group)

    lines: list[str] = [
        "# ── dbt schema.yml ───────────────────────────────────────────────────────────",
        "# Generated by ByeDataClean export_quality_checks.py",
        f"# Source: {rules_path}",
        "# STARTER TEMPLATE — review and adapt before use in production.",
        "# See: https://docs.getdbt.com/reference/resource-properties/tests",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        "version: 2",
        "",
        "models:",
        f"  - name: {model_name}",
        "    description: >",
        "      Auto-generated from ByeDataClean cleaning rules. Add your own description.",
        "    columns:",
    ]

    # Track unique-key columns for generating unique tests
    single_unique_cols: set[str] = {
        key_group[0] for key_group in unique_keys if len(key_group) == 1
    }

    for col in sorted(all_cols):
        lines.append(f"      - name: {col}")
        tests: list[str] = []

        if col in required_cols:
            tests.append("not_null")
        if col in single_unique_cols:
            tests.append("unique")
        if col in accepted_values:
            vals = accepted_values[col]
            tests.append(
                "accepted_values:\n"
                f"              values: {vals!r}"
            )
        if col in ranges:
            r = ranges[col]
            mn = r.get("min")
            mx = r.get("max")
            if mn is not None:
                tests.append(
                    f"dbt_utils.expression_is_true:\n"
                    f"              expression: \"{col} >= {mn}\""
                )
            if mx is not None:
                tests.append(
                    f"dbt_utils.expression_is_true:\n"
                    f"              expression: \"{col} <= {mx}\""
                )

        if tests:
            lines.append("        tests:")
            for t in tests:
                first_line = t.split("\n")[0]
                rest_lines = t.split("\n")[1:]
                lines.append(f"          - {first_line}")
                for rl in rest_lines:
                    lines.append(f"            {rl}")

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "schema.yml"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ── Pandera exporter ──────────────────────────────────────────────────────────

def export_pandera(
    validation: dict[str, Any],
    schema_cfg: dict[str, Any] | None,
    output_dir: Path,
    rules_path: str = "",
) -> Path:
    """Generate a Pandera DataFrameSchema skeleton."""
    required_cols: list[str] = validation.get("required_columns") or []
    unique_keys: list[list[str]] = validation.get("unique_keys") or []
    accepted_values: dict[str, list] = validation.get("accepted_values") or {}
    ranges: dict[str, dict] = validation.get("ranges") or {}

    all_cols: set[str] = set(required_cols) | set(accepted_values) | set(ranges)
    for key_group in unique_keys:
        all_cols.update(key_group)

    single_unique_cols: set[str] = {
        key_group[0] for key_group in unique_keys if len(key_group) == 1
    }

    # Infer types from schema_cfg if provided
    col_types: dict[str, str] = {}
    if schema_cfg:
        for col, cfg in (schema_cfg.get("columns") or {}).items():
            t = cfg.get("type", "")
            role = cfg.get("role", "")
            if role == "id" or t in ("categorical", "binary"):
                col_types[col] = "str"
            elif t == "continuous":
                col_types[col] = "float"
            elif t == "date":
                col_types[col] = "datetime"
            else:
                col_types[col] = "object"

    lines: list[str] = [
        '"""',
        "Pandera DataFrameSchema — generated by ByeDataClean export_quality_checks.py",
        f"Source: {rules_path}",
        "STARTER TEMPLATE — review and adapt before use in production.",
        "See: https://pandera.readthedocs.io/",
        '"""',
        "",
        "import pandera as pa",
        "from pandera import Column, DataFrameSchema, Check",
        "",
        "",
        "schema = DataFrameSchema(",
        "    {",
    ]

    for col in sorted(all_cols):
        dtype = col_types.get(col, "object")
        nullable = col not in required_cols
        unique = col in single_unique_cols

        checks: list[str] = []
        if col in accepted_values:
            vals = accepted_values[col]
            checks.append(f"Check.isin({vals!r})")
        if col in ranges:
            r = ranges[col]
            mn = r.get("min")
            mx = r.get("max")
            if mn is not None and mx is not None:
                checks.append(f"Check.between({mn}, {mx})")
            elif mn is not None:
                checks.append(f"Check.greater_than_or_equal_to({mn})")
            elif mx is not None:
                checks.append(f"Check.less_than_or_equal_to({mx})")

        checks_str = f"[{', '.join(checks)}]" if checks else "None"
        unique_str = f", unique={unique}" if unique else ""
        lines.append(
            f'        "{col}": Column({dtype!r}, {checks_str}, '
            f'nullable={nullable}{unique_str}),'
        )

    lines += [
        "    },",
        "    coerce=False,",
        "    strict=False,  # allow extra columns not listed here",
        ")",
        "",
        "",
        "if __name__ == '__main__':",
        "    import pandas as pd",
        "    # Example: validate a DataFrame",
        "    # df = pd.read_csv('data/processed/your_cleaned_file.csv')",
        "    # schema.validate(df)",
        "    print('Schema loaded. Call schema.validate(df) to validate a DataFrame.')",
    ]

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "schema.py"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ── Soda exporter ─────────────────────────────────────────────────────────────

def export_soda(
    validation: dict[str, Any],
    output_dir: Path,
    dataset_name: str = "my_dataset",
    rules_path: str = "",
) -> Path:
    """Generate a Soda Core checks.yml."""
    required_cols: list[str] = validation.get("required_columns") or []
    unique_keys: list[list[str]] = validation.get("unique_keys") or []
    accepted_values: dict[str, list] = validation.get("accepted_values") or {}
    ranges: dict[str, dict] = validation.get("ranges") or {}

    lines: list[str] = [
        "# ── Soda Core checks.yml ─────────────────────────────────────────────────────",
        "# Generated by ByeDataClean export_quality_checks.py",
        f"# Source: {rules_path}",
        "# STARTER TEMPLATE — review and adapt before use in production.",
        "# See: https://docs.soda.io/soda-cl/soda-cl-overview.html",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        f"checks for {dataset_name}:",
    ]

    # Required columns → missing_count = 0
    for col in required_cols:
        lines.append(f"  - missing_count({col}) = 0:")
        lines.append(f"      name: \"{col} must not be null\"")

    # Unique keys → duplicate_count = 0
    for key_group in unique_keys:
        if len(key_group) == 1:
            col = key_group[0]
            lines.append(f"  - duplicate_count({col}) = 0:")
            lines.append(f"      name: \"{col} must be unique\"")
        else:
            # Composite key: Soda doesn't have native composite unique checks; comment it
            key_str = ", ".join(key_group)
            lines.append(f"  # Composite unique key [{key_str}] — implement as custom check or dbt test")

    # Accepted values → invalid_count = 0
    for col, vals in accepted_values.items():
        lines.append(f"  - invalid_count({col}) = 0:")
        lines.append(f"      valid values:")
        for v in vals:
            lines.append(f"        - {v!r}")
        lines.append(f"      name: \"{col} must be in accepted values\"")

    # Ranges → min/max
    for col, r in ranges.items():
        mn = r.get("min")
        mx = r.get("max")
        if mn is not None:
            lines.append(f"  - min({col}) >= {mn}:")
            lines.append(f"      name: \"{col} must be >= {mn}\"")
        if mx is not None:
            lines.append(f"  - max({col}) <= {mx}:")
            lines.append(f"      name: \"{col} must be <= {mx}\"")

    lines.append("")
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "checks.yml"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ── CLI ────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="export_quality_checks.py",
        description="Export ByeDataClean rules to dbt, Pandera, or Soda starter files.",
    )
    p.add_argument("--rules",  metavar="PATH",
                   help="Path to a YAML cleaning rules file (source of validation checks).")
    p.add_argument("--schema", metavar="PATH",
                   help="Path to a YAML schema file (optional — used for Pandera type hints).")
    p.add_argument("--target", required=True, choices=["dbt", "pandera", "soda"],
                   help="Output framework: dbt, pandera, or soda.")
    p.add_argument("--output", metavar="DIR", default="exports",
                   help="Output directory (default: exports/).")
    p.add_argument("--model-name", metavar="NAME", dest="model_name",
                   default="my_model",
                   help="Model/dataset name used in the generated file (default: my_model).")
    return p


def main() -> None:
    args = _build_parser().parse_args()

    if not args.rules and not args.schema:
        print("Error: at least one of --rules or --schema must be provided.", file=sys.stderr)
        sys.exit(1)

    validation: dict[str, Any] = {}
    rules_path = ""
    if args.rules:
        rules = load_rules(args.rules)
        validation = rules.get("validation", {}) or {}
        rules_path = args.rules

    schema_cfg: dict[str, Any] | None = None
    if args.schema:
        with open(args.schema) as fh:
            schema_cfg = yaml.safe_load(fh) or {}

    output_dir = Path(args.output)
    target = args.target

    if target == "dbt":
        target_dir = output_dir / "dbt"
        out = export_dbt(validation, target_dir, args.model_name, rules_path)
        print(f"  ✓ dbt schema    → {out}")

    elif target == "pandera":
        target_dir = output_dir / "pandera"
        out = export_pandera(validation, schema_cfg, target_dir, rules_path)
        print(f"  ✓ Pandera schema → {out}")

    elif target == "soda":
        target_dir = output_dir / "soda"
        out = export_soda(validation, target_dir, args.model_name, rules_path)
        print(f"  ✓ Soda checks   → {out}")

    print(f"\n  STARTER TEMPLATE — review before use in production.")


if __name__ == "__main__":
    main()
